[tool.briefcase]
project_name = "Bhaskara"
bundle = "com.bhaskara"
version = "0.0.1"
url = "https://www.linkedin.com/in/whebertonfialho/"
license = "BSD license"
author = 'Wheberton Fialho'
author_email = "whebertonfialho@gmail.com"

[tool.briefcase.app.bhaskara]
formal_name = "Bhaskara"
description = "App que calcula a formula de Bhaskara"
icon = "src/bhaskara/resources/bhaskara"
sources = ['src/bhaskara']
requires = []


[tool.briefcase.app.bhaskara.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.bhaskara.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.bhaskara.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.bhaskara.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.bhaskara.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
